Kernel
lanl/qmd-progress pull request #169
Opened 2021-05-12 18:02 UTC by linneamk

O(N) implementation of pre-conditioned kernel calculation using implicit Fermi-Dirac response calculations.

2021-05-14 17:53 UTC, nicolasbock commented
Sorry for the delay @linneamk . Our CI tests are currently broken because we were using Travis-CI who changed their business model and stopped offering their free open source software support. We will have to switch to GitHub Actions before we can run CI again. If anyone else can verify manually that this PR is passing the tests I am happy to merge it.

2021-06-04 02:56 UTC, nicolasbock commented
Could you rebase this PR? We just merged a fix for CI into master.

2021-06-04 12:26 UTC, nicolasbock commented
I rebased the change.

2021-06-04 12:36 UTC, nicolasbock requested changes
The CI tests are failing:

https://github.com/lanl/qmd-progress/runs/2745932751?check_suite_focus=true#step:5:639

Please have a look.

2021-07-16 16:38 UTC, linneamk commented
Hi! Sorry for my delay, I have updated my code and fixed the test.

2021-07-17 11:09 UTC, nicolasbock commented
Thanks @linneamk . You need to rebase your changes. Right now the merge conflicts prevent us from merging the pull request.

Thanks!

2021-07-18 11:55 UTC, nicolasbock commented
Thanks @linneamk .

Something went wrong during the rebase though. What commands did you run to rebase?

2021-09-15 22:45 UTC, cnegre approved these changes

2021-09-17 17:25 UTC, nicolasbock requested changes
Do you need help cleaning up your rebase?

2021-09-17 22:05 UTC, nicolasbock commented
Hi @linneamk 

I spent a good hour just now trying to rebase your commits onto the current `master` branch. Unfortunately I ran into a wall and was not able to complete the rebase.

You had based the original PR on a rather old commit (4e73df7664d468ed0ba213bf21768ef41a5adb3d). I rebased that commit in https://github.com/lanl/qmd-progress/pull/169#issuecomment-854667688 as 0d6316ba4207841877075fa6dbd8d24e5436f7ba.

However, you ignored that rebase and force pushed 02e93a6c87bbfaa9fdfd775ee5c4b77c10f0f0fd which was still based on this old commit.

After asking you to rebase you _merged_ your branch with `master` instead and pushed 6304e52fbc1f45de355658e384d72acab31c580a which is quite frankly a bit of a mess. Your PR now contains duplicate commits

```
* 6304e52 Fixed indentation
*   f5eeefd Rebased
|\  
| *   1fe5601 Merge branch 'master' into kernel
| |\  
| * | 02e93a6 Fixed test
| * | 2ac9f50 Added kernel routine
| * | 7960bcf O(N) pre-conditioned kernel matrix with implicit FD-expansion response
| * | 383736e Added kernel routines for XL-BOMD
* | | 1256e74 Fixed test
* | | da4eb81 Added kernel routine
* | | bf9a368 O(N) pre-conditioned kernel matrix with implicit FD-expansion response
* | | ce0e474 Added kernel routines for XL-BOMD
| |/  
|/|   
* |   eab14aa Merge pull request #201 from nicolasbock/ci_scripts
```

and it's unclear to me whether your changes are even correctly represented in your branch.

Merging does not always produce the desired code since the merging algorithm is really pretty dumb because it doesn't know what your intention and the intention of the person making changes in the branch you merged with was when the changes were made. It's really a best guess kind of effort.

Could you carefully go through your original changes and apply them to a fresh branch that is based on the current `master` branch?

Please don't hesitate to ask if any of what I wrote is unclear. `Git` is a little tricky to use :smile:

Thanks.

2021-09-18 11:06 UTC, linneamk commented
Hi! 

Wow, I'm sorry and thank you for trying to clean up my mess  😅  I will try to create a new branch and commit my changes to, I'll
let you know if I need any help. Thanks!

2021-09-18 13:19 UTC, nicolasbock commented
Thanks @linneamk ! Don't hesitate to ask if you run into any difficulties.

2023-10-13 17:35 UTC, jeanlucf22 commented
@linneamk Are you still working on this one? Or did these changes make it into another PR?

2025-08-05 21:13 UTC, closed without merging