C interface for progress functions
lanl/qmd-progress pull request #262
Opened 2023-07-06 21:06 UTC by ares201005

C test for density matrix module (passed!)
Python script to generate c wrappers and headers
Add c interface for prg_chebyshev_mod module (Tests TBA) 
Add c interface for prg_charges_mod (Tests TBA)

PS: 
1) I found I cannot re-pen previous PR, so created a new PR (will not close it this time). 
2) There are some ci tests fail, I will continue working on them.  In the meanwhile, please comment on the code. 
3) I am working on the rest of the modules and corresponding tests as well, will push them into this PR once ready.

2023-07-06 21:08 UTC, ares201005 commented on tests/CMakeLists.txt
> +progress_test(prg_density_c)
All the c test names end with "_c" in order to avoid conflicts with Fortran test names.

2023-07-06 21:53 UTC, ares201005 commented
Now all the CI checks passed!

2023-07-07 01:16 UTC, jeanlucf22 commented on benchmarks/dmconstruction/dmconstruction.F90
> +  !integer, external :: iargc
remove

2023-07-07 01:17 UTC, jeanlucf22 commented on examples/c_interface/progress.c
> +    //prg_progress_init_c();   // initialize progress
why keep these commented lines?

2023-07-07 01:18 UTC, jeanlucf22 commented on examples/c_interface/scf.c
> +#include <stdlib.h>
what is this code supposed to do? Is 'scf' a good name for it? Please add comments

2023-07-07 01:26 UTC, jeanlucf22 requested changes

2023-07-07 01:26 UTC, jeanlucf22 commented on scripts/transform.py
> +import re
Please add comments describing what this code is doing

2023-07-07 01:26 UTC, jeanlucf22 commented on scripts/transform.py
> +    #subroutine_re = re.compile(r'subroutine\s+([a-zA-Z0-9_]+)\s*\((.*)\)')
remove commented lines unless they have a purpose/could be useful later

2023-07-07 01:26 UTC, jeanlucf22 commented on src/CMakeLists.txt
> +  #prg_densitymatrix_mod_c.F90)
remove commented lines

2023-07-07 01:26 UTC, jeanlucf22 commented on src/prg_c_interface.F90
> +  subroutine prg_build_density_T_c(norbs, ham_bml_c, rho_bml_c, threshold, bndfil, kbt, ef, eigenvalues_out) bind(C, name="prg_build_density_T")
could you split these long lines?

2023-07-07 01:26 UTC, jeanlucf22 commented on src/prg_c_interface.F90
> +  !  subroutine prg_parse_system_c(system, filename, extin) bind(C, name="prg_parse_system")
are all these commented lines useful?

2023-07-07 01:26 UTC, jeanlucf22 commented on tests/src/main.c
> +    /*
remove commented lines

2023-07-07 01:26 UTC, jeanlucf22 commented on tests/src/main.c
> +    double *eigenvalues = malloc(norb * sizeof(double));
I don't see a free() corresponding to this malloc

2023-07-13 01:51 UTC, jeanlucf22 commented on examples/c_interface/scf.c
> +#include <stdlib.h>
I still do not understand what this file is about. Maybe it should not be added yet?

2023-07-13 04:20 UTC, ares201005 commented
Changes: 1) Removed scf.c and other commented lines; 2) Added sp2 tests.

2023-07-13 04:37 UTC, ares201005 commented
hmm, two CI tests fail on sp2, will work on the fix.

2023-07-13 11:21 UTC, jeanlucf22 approved these changes

2023-07-14 08:35 UTC, nicolasbock commented on scripts/transform.py
> +   pattern = re.compile(r'public ::(.*)')
```suggestion
   pattern = re.compile(r'public *::(.*)')
```
The standard does not require exactly one whitespace after the public keyword.

2023-07-19 15:56 UTC, ares201005 commented
Now this PR can be merged. Thanks.

2023-07-20 05:10 UTC, nicolasbock approved these changes

2023-07-20 05:10 UTC, merged